version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: page-carnival-app
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/page_carnival
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: page-carnival-postgres
    environment:
      POSTGRES_DB: page_carnival
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: