version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: page-carnival-postgres
    environment:
      POSTGRES_DB: page_carnival
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: